INVALID_NUMBER_OF_ARG = "Invalid number of arguments"
INVALID_LENGTH_CRON_EXPR = "Invalid length of cron expression"
INVALID_EXPR_RANGE = "Invalid range in expression"
INVALID_EXPR_FORMAT = "Invalid expression format"
INVALID_TIME_FORMAT = "Invalid time format"
